:toc: macro
:toc-levels: 4
:toc-title: Содержение
ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= Project Mariotte

Проект Мариотт - это демо проект https://azhidkov.pro/ergo-approach/landing/[Эргономичного подхода] на примере сервиса бронирования номеров в отелях.

toc::[]

== Карта проекта

. Код иллюстрирующий Эргономичный подход
.. Тестирование
... Тесты на поведение
... Эффективный запуск реального PostgreSQL
... Доменно-спецефичный матчер
... Генерация случайных тестовых данных
... ObjectMothers
.. Неизменяемая модель данных
.. Структурный дизайн
.. Модель на базе диаграммы эффектов
... Простая операция
... Сложная операция
... Простой ресурс
... Сложный ресурс
.. Кодирование
... Обход проблемы интеграции Spring Transactions с Kotlin Result
... "Очевидизация" вариантов ответов эндпоинта

. Прочие "Points of interest"
.. Верификация Json-схем
.. Problem Details
... ErrorResponse
... UnhandledExceptionsHandler
.. PostgreSQL generate_series
.. Пессимистичные блокировки в Spring Data JDBC
.. Kotlin value-класс
.. Реестр Json-схем

== "Техническое задание"

* Сервис должен обеспечивать бронирования номеров в разных отелях;
* Сервис должен поддерживать типы номероров, определённых международным стандартом ISO 404:404 - люкс и полулюкс;
* Бронировние определяет только тип номера, но не конкрентный номер.
Конкретный номер выбирает администратор при заселении гостя;
* Сервис должен исключать овербукинг - создание большего количества броней номеров определённого типа в одном отеле за определённую дату, чем есть в целом номеров данного типа в отеле;
* Сервис должен недопускать бронирования, начинающиеся ранее следующих суток относительно момента времени запроса на бронирование.

== Системная аналитика

=== Модель предметной области

image::docs/images/ER.drawio.svg[]

[NOTE]
====
Модель предметной области представлена https://azhidkov.pro/microposts/23/11/immutable-relation-data-model-v2/[Эргономичной нотации ER-модели]
====

=== Спецификация HTTP API

[NOTE]
====
Этот раздела написан в моём самодельном легковесном и слабоформализованном формате описания HTTP-эндпоинтов.

Маппинг ошибок на коды статусов выполнен в соответствии с https://github.com/ergonomic-code/Ergo-Approach-Guideline/wiki/Проектирование-HTTP-API#коды-ошибок[гайдлайном эргономичного подхода].
====

*Модель RoomReservationRequest*

[source]
----
{
  "hotelId": <number>
  "roomType": <number>
  "email": <string:email>
  "from": <string:iso-8601 date>
  "period": <string:iso-8601 duration>
}
----

*Модель ReservationSuccess*

[source]
----
{
  "reservationId": <number>
}
----

*Модель ErrorResponse*

Соответсвтует спецификации https://datatracker.ietf.org/doc/html/rfc7807[Problem Details for HTTP APIs], всегда содержит дополнительное свойство timestamp.

[source]
----
{
  "timestamp": <string:iso-8601 timestmap>,
  "instance": <string>,
  "status": <number:200..600>,
  "type": <string>
  "title": <string>
  "details": <string>
}
----

*Метод reserveRoom*

Метод бронирования комнаты в отеле на период.

Предусловия:

* Передан идентификатор отеля, существующий в БД;
* Передан корректный тип номера;
* В заданном отеле есть номера заданного типа;
* Переданная дата "от" находится в будущем, не менее чем на один день от момента поступления запроса;
* Длительность периода составляет один или более дней;
* В запрошенном отеле за каждый запрошенный день есть свободный номер запрошенного типа.

Постусловия:

* В БД в коллекцию бронирований добавлен добавлена бронь, соответсвующая запросу;
* Количество досутпных номеров указанного типа за указанный период уменьшено на 1.

[source]
----
POST /guest/reservations
>
  <RoomReservationRequest>

<
  201
    <OrderCreated>

  400
    <RequestFailed:reservation-dates-in-past> // до даты начала резервации осталось менее дня

  400
    <RequestFailed:invalid-reservation-dates> // дата резервации "до" меньше либо равна дате "от"

  400
    <RequestFailed> // некорректный зарос

  409
    <RequestFailed:hotel-not-found> // отель с указанным идентификатором не найден

  409
    <RequestFailed:room-type-not-found> // номер указанного типа в отеле с указанным идентификатором не найден

  409
    <RequestFailed:no-available-rooms> // за запрошенные даты в отеле нет свободных комнат запрошенного типа

  500
    <RequestFailed> // при обработке запроса произошла ошибка

----

=== Диаграмма эффектов

=== Диаграмма классов

=== Структурная схема

=== Структура пакетов

== Требования к окружению

== Запуск тестов

== Сборка проекта

== Запуск проекта

=== Примеры запросов